In [2]:
def eigh(F, v):
    X = np.eye(100,1)
    X [:,0]= v[0:100, 0]
    lamb = []
    i = 0 
    
    while True:
        X1 = np.dot(F,X)
        lamb.append (X1[0, 0] / X[0, 0])
        X = X1
        if i>0:
            if abs((lamb[i] - lamb[i-1])) < 0.1 or i>100:
                break
        i += 1
    return lamb[i]

In [10]:
#Определение минимального собственного значения эрмитовой матрицы
#Метод итераций для нахождения собственных значений

from math import *
import numpy as np

a = input(u'Значение a: ')

#        if func(N , M , a) < Emin:
#            Emin = func(N , M , a)

def func(N , M , a):
    return sin((N+M)**(0.5*1.5)/log(N+M+a))

Emin = func(1 , 1 , a)
F = np.eye(100)

for N in xrange(1,101):
    for M in xrange(1,101):
#        F[N - 1 , M - 1] = func(N , M , a)
        if M  == N:
           F[N - 1 , M - 1] = M 

w, v = np.linalg.eigh(F)

print "Собственное значение:\n", round(eigh(F,v),5), '\n'

#print 'Emin: ', Emin

Значение a: 1
Собственное значение:
1.0 



In [160]:
from math import *
import numpy as np

def eigh(F, v):
    X = np.array([[1.], [1], [1]])
    lamb = []
    i = 0 
    
    while True:
        X1 = np.dot(F,X)
        lamb.append (X1[0, 0] / X[0, 0])
        X = X1
        if i>0:
            if abs((lamb[i] - lamb[i-1])) < 0.1 or i>400:
                break
        i += 1
    return lamb , i


F = np.array([[5, 1, 2], [1, 4, 1], [2, 1, 3]])
w, v = np.linalg.eigh(F)

print "Собственное число:\n", eigh(F,v), '\n', F, w

Собственное число:
([8.0, 7.25, 7.0344827586206895, 6.9558823529411766], 3) 
[[5 1 2]
 [1 4 1]
 [2 1 3]] [ 1.70759841  3.39729507  6.89510652]


In [188]:
F = np.array([[5, 1, 2], [1, 4, 1], [2, 1, 3]])
for i in range(3):
    if i % 2 != 0:
        F [i,0] = 0
print F

[[5 1 2]
 [0 4 1]
 [2 1 3]]


In [9]:
#Определение минимального собственного значения эрмитовой матрицы
#Метод итераций для нахождения собственных значений

from math import *
import numpy as np

a = input(u'Значение a: ')

def func(N , M , a):
    return np.float64(sin((N+M)**(0.5*1.5)/log(N+M+a)))

F = np.eye(100)

for N in xrange(1,101):
    for M in xrange(1,101):
        F[N - 1 , M - 1] = func(N , M , a)
        
def eigh(F, v):
    X = np.eye(100,1)
    X [:,0]= v[0:100, 0]
    for i in range(100):
        if i % 10 == 0:
            X [i,0] = 1
            
    lamb2 = 0
    i = 0 
    
    while True:
        X1 = np.dot(F,X)
        lamb1 = lamb2
        lamb2 = (X1[0, 0] / X[0, 0])
        X = X1
        print lamb2
        if i>0:
            if abs(lamb2 - lamb1) < 1 or i>150:
                break
        i += 1
    return lamb2

w, v = np.linalg.eigh(F)

print "Собственное число:\n", w.min(), eigh(F, v)

Значение a: 1
Собственное число:
-48.5621080326 0.0214588773783
-8654.53470373
25.95620148
107.209139523
25.1854606089
97.7849748587
25.9533706736
94.2536374683
26.7905631974
91.3037869534
27.6127482311
88.6173278723
28.4141798666
86.1505297226
29.1944206819
83.8792033937
29.9534359
81.7832187446
30.6912612082
79.8451187834
31.4079780302
78.0496540328
32.1037093079
76.38344174
32.7786166107
74.8346882742
33.4328973155
73.3929597978
34.0667817961
72.0489915925
34.6805306361
70.7945286389
35.2744318842
69.6221916307
35.8487983673
68.5253638121
36.4039650763
67.4980949549
36.9402866357
66.535019523
37.4581348686
65.6312866344
37.9578964639
64.7824998828
38.4399707534
63.9846654362
38.9047676028
63.2341471117
39.3527054211
62.5276273575
39.7842092892
61.8620732524
40.1997092095
61.2347067862
40.5996384759
60.6429788038
40.9844321622
60.0845460955
41.354525729
59.5572511992
41.7103537431
59.0591045447
42.0523487092
58.5882686305
42.3809400081
58.1430439657
42.696552937
57.7218565516
42.9996